name: build
on:
 push:
   branches:
     - main
jobs:
  build:
    runs-on: [fedora-latest]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: '0' # default is '1'
        fetch-tags: true # default is false
        lfs: true # default is false
    - name: Login to container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.GITHUB_SERVER_URL }}
        username: ${{ env.GITHUB_ACTOR }}
        password: ${{ secrets.AUTH_TOKEN }}
    - name: build and push
      run: PUSH=1 ./build.sh
